name: wf1

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "wf1 created"
      - name: Copy Code
        uses: actions/checkout@v6
      - name: List Repo Files
        run: ls -la
